sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJ7mfSbAqvG6TMxqKfK
    access-key-secret: I3mtBBw07wF6OgCi2J8Af0N9UWDYQC
    bucket-name: picturestore-gaoxl

  redis:
    host: localhost
    port: 6379

  wechat:
    appid: wx2aec228fa45a1f69
    secret: 15a06915cdfaefddeda15f9f6fa8e9da