sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJ7mfSbAqvG6TMxqKfK
    access-key-secret: I3mtBBw07wF6OgCi2J8Af0N9UWDYQC
    bucket-name: picturestore-gaoxl

  redis:
    host: localhost
    port: 6379

  wechat:
    appid: wx2aec228fa45a1f69
    secret: 15a06915cdfaefddeda15f9f6fa8e9da
    mchid: 1602141350
    mchSerialNo: 7
    privateKeyFilePath: classpath:apiclient_key.pem
    apiV3Key: 8
    weChatPayCertFilePath: classpath:apiclient_cert.pem
    notifyUrl:  http://5fea57fe.r26.cpolar.top/pay/notify
    refundNotifyUrl:  http://5fea57fe.r26.cpolar.top/pay/refundNotify
